added event and task classes
Dachi-Laperashvili/event-organizer pull request #1
Opened 2023-06-17 17:25 UTC by Dachi-Laperashvili

2023-06-19 07:40 UTC, giorobota requested changes
Good job, I left some small comments, please update your commit message according to conventional commits https://www.conventionalcommits.org/en/v1.0.0/

Also, let's include flyway migrations in this PR as well:
https://www.baeldung.com/database-migrations-with-flyway

2023-06-19 07:40 UTC, giorobota commented on src/main/java/com/example/eventorganizer/task/State.java
> +public enum State {
Please rename it to TaskState so we know where this enum belongs

2023-06-19 07:40 UTC, giorobota commented on src/main/java/com/example/eventorganizer/task/Task.java
> +@Entity
Add one line separation between imports and code

2023-06-21 14:23 UTC, giorobota requested changes

2023-06-21 14:23 UTC, giorobota commented on src/main/resources/db/migration/V1__.sql
> +CREATE TABLE IF NOT EXISTS events
Please move each table creation to separate file

2023-06-21 14:23 UTC, giorobota commented on src/main/resources/application.properties
> +spring.flyway.password=password
Passwords should not be visible in git repository. You may have also received github's security warning email.
You can pass passwords as environment variables, like 
`spring.flyway.password=${DB_PASSWORD}`
and run application with parameters DB_PASSWORD=password

2023-06-21 14:30 UTC, giorobota commented on src/main/resources/application.properties
> +spring.flyway.password=password
https://www.jetbrains.com/help/objc/add-environment-variables-and-program-arguments.html

2023-06-22 12:50 UTC, giorgi-robitashvili approved these changes

2023-06-22 12:50 UTC, giorgi-robitashvili approved these changes

2023-06-22 13:05 UTC, merged